### ISSUE TITLE
Notruf crashed beim Click auf den Aufnahmeknopf

### ISSUE THREAD

**Issue by lhoff94** [fub-agdb/tierklinik_app#34]
```E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.fu_berlin.mi.tierklinik, PID: 27907
                  java.lang.RuntimeException: setAudioSource failed.
                      at android.media.MediaRecorder._setAudioSource(Native Method)
                      at android.media.MediaRecorder.setAudioSource(MediaRecorder.java:699)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity.startRecording(NotrufActivity.java:83)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity.access$100(NotrufActivity.java:33)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity$1.onTouch(NotrufActivity.java:64)
                      at android.view.View.dispatchTouchEvent(View.java:12536)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3384)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:563)
                      at android.view.View.dispatchPointerEvent(View.java:12788)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5670)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5465)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7736)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7676)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7637)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7847)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:197)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:325)
                      at android.os.Looper.loop(Looper.java:142)
                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by lhoff94** [comment]
Ein Problem war das in neueren Versionen von Android bei bestimmten Permissions um Erlaubnis gefragt werden muss. Das Mikrofon ist auch so eine Permission.


Danach kommt aber eine IllegalStateException:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.fu_berlin.mi.tierklinik, PID: 16483
                  java.lang.IllegalStateException
                      at android.media.MediaRecorder._start(Native Method)
                      at android.media.MediaRecorder.start(MediaRecorder.java:1309)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity.startRecording(NotrufActivity.java:117)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity.access$100(NotrufActivity.java:36)
                      at de.fu_berlin.mi.tierklinik.notruf.NotrufActivity$1.onTouch(NotrufActivity.java:87)
                      at android.view.View.dispatchTouchEvent(View.java:12536)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3384)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:563)
                      at android.view.View.dispatchPointerEvent(View.java:12788)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5670)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5465)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7736)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7676)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7637)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7847)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:197)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:325)
                      at android.os.Looper.loop(Looper.java:142)
                      at android.app.ActivityThread.main(ActivityThread.java:6944)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
