### ISSUE TITLE
App Crashed bei Notfallordner

### ISSUE THREAD

**Issue by lhoff94** [fub-agdb/tierklinik_app#6]
Bei Aufrufen eines beliebigen Notfallordners beendet sich die App.

Stacktrace aus dem Emulator:
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.fu_berlin.mi.tierklinik, PID: 6384
                  android.os.FileUriExposedException: file:///storage/emulated/0/testthreepdf/pdfFile.pdf exposed beyond app through Intent.getData()
                      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
                      at android.net.Uri.checkFileUriExposed(Uri.java:2371)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:10247)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:10222)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:10201)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1667)
                      at android.app.Activity.startActivityForResult(Activity.java:4586)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:4544)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                      at android.app.Activity.startActivity(Activity.java:4905)
                      at android.app.Activity.startActivity(Activity.java:4873)
                      at de.fu_berlin.mi.tierklinik.notfallordner.TopicActivity.view(TopicActivity.kt:85)
                      at de.fu_berlin.mi.tierklinik.notfallordner.TopicActivity.getPDF(TopicActivity.kt:73)
                      at de.fu_berlin.mi.tierklinik.notfallordner.TopicActivity.access$getPDF(TopicActivity.kt:22)
                      at de.fu_berlin.mi.tierklinik.notfallordner.TopicActivity$onCreate$1.onItemClick(TopicActivity.kt:43)
                      at android.widget.AdapterView.performItemClick(AdapterView.java:318)
                      at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
                      at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
                      at android.widget.AbsListView.onTouchUp(AbsListView.java:4064)
                      at android.widget.AbsListView.onTouchEvent(AbsListView.java:3822)
                      at android.view.View.dispatchTouchEvent(View.java:12513)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
                      at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
                      at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:3400)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
                      at android.view.View.dispatchPointerEvent(View.java:12752)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
E/AndroidRuntime:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:326)
                      at android.os.Looper.loop(Looper.java:160)
                      at android.app.ActivityThread.main(ActivityThread.java:6669)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 6384 SIG: 9`

**Comment by lhoff94** [comment]
Das Problem scheint mit einer neueren Android Version zusammenzuhängen. 
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by jastephan** [comment]
replace file:// URI with content:// URI
fixt
android.os.FileUriExposedException: file:///storage/emulated/0/testthreepdf/pdfFile.pdf exposed

im Moment wird aber eine NullPointerException geworfen
code in iss06

**Comment by jastephan** [comment]
also wie ich das im Mom sehe, wird die PDF Datei in einem internen App Ordner gesucht, in dem Sie aber nicht liegt..
ka bis jetzt wie man das lösen kann

**Comment by lhoff94** [comment]
Hast du mal die stelle gesucht an der die PDF heruntergelade wird und dort abgelegt wird. 
Die Datei wird ja on the Fly heruntergeladen. Und zwar gibt es ja das FileDownloader Objekt das in \tierklinik_app\tierklinik_app\app\src\main\java\de\fu_berlin\mi\tierklinik\notfallordner\FileDownloader.kt definiert ist und in \tierklinik_app\tierklinik_app\app\src\main\java\de\fu_berlin\mi\tierklinik\notfallordner\TopicActivity.kt in der funktion getPDF aufgerufen wird. Dort bekommt das Objekt auch einen Pfad und filename übergeben.

**Comment by lhoff94** [comment]
immernoch offen, Notfallordner ist in der App aber deaktiviert.
